-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
        files: \.(js|rb|md|py|sh|txt|yaml|yml)$
    -   id: check-json
        files: \.(json|template)$
    -   id: check-yaml
        files: \.(yml|yaml)$
    -   id: detect-private-key
    -   id: detect-aws-credentials
-   repo: git://github.com/detailyang/pre-commit-shell
    sha: 6f03a87e054d25f8a229cef9005f39dd053a9fcb
    hooks:
    -   id: shell-lint
